services:

  app:
    build: .
    container_name: kappa-app
    restart: unless-stopped
    environment:
      - PORT=3000
      - NODE_ENV=production
      - JWT_SECRET=2dYGxJg!WYVhL!7kg!k*TYyc^bqep@zP376F6SeoSkca!BgAi6
    volumes:
      - ./eft_tracker.db:/app/eft_tracker.db
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
